FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        desktop-file-utils \
        ethtool \
        file \
        libexpat1 \
        libfontconfig1 \
        libfreetype6 \
        libcap2-bin \
        libpcap0.8 \
        zlib1g && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /work
